version: '3'
services:
  contract-verifier:
    image: matterlabs/contract-verifier:9cada1a-1701108819338
    environment:
      - CONTRACT_VERIFIER_COMPILATION_TIMEOUT=30
      - CONTRACT_VERIFIER_POLLING_INTERVAL=1000
      - CONTRACT_VERIFIER_PROMETHEUS_PORT=3314
      - API_WEB3_JSON_RPC_HTTP_PORT=3050
      - API_WEB3_JSON_RPC_HTTP_URL=http://127.0.0.1:3050
      - API_WEB3_JSON_RPC_WS_PORT=3051
      - API_WEB3_JSON_RPC_WS_URL=ws://127.0.0.1:3051
      - API_WEB3_JSON_RPC_REQ_ENTITIES_LIMIT=10000
      - API_WEB3_JSON_RPC_FILTERS_LIMIT=10000
      - API_WEB3_JSON_RPC_SUBSCRIPTIONS_LIMIT=10000
      - API_WEB3_JSON_RPC_PUBSUB_POLLING_INTERVAL=200
      - API_WEB3_JSON_RPC_THREADS_PER_SERVER=128
      - API_WEB3_JSON_RPC_MAX_NONCE_AHEAD=5
      - API_WEB3_JSON_RPC_GAS_PRICE_SCALE_FACTOR=1.2
      - API_WEB3_JSON_RPC_TRANSACTIONS_PER_SEC_LIMIT=1000
      - API_WEB3_JSON_RPC_REQUEST_TIMEOUT=10
      - API_WEB3_JSON_RPC_ACCOUNT_PKS=0x0000000000000000000000000000000000000000000000000000000000000001,0x0000000000000000000000000000000000000000000000000000000000000002
      - API_WEB3_JSON_RPC_ESTIMATE_GAS_SCALE_FACTOR=1.0
      - API_WEB3_JSON_RPC_ESTIMATE_GAS_ACCEPTABLE_OVERESTIMATION=1000
      - API_WEB3_JSON_RPC_MAX_TX_SIZE=1000000
      - API_WEB3_JSON_RPC_VM_CONCURRENCY_LIMIT=512
      - API_WEB3_JSON_RPC_FACTORY_DEPS_CACHE_SIZE_MB=128
      - API_WEB3_JSON_RPC_INITIAL_WRITES_CACHE_SIZE_MB=32
      - API_WEB3_JSON_RPC_LATEST_VALUES_CACHE_SIZE_MB=256
      - API_WEB3_JSON_RPC_HTTP_THREADS=128
      - API_WEB3_JSON_RPC_WS_THREADS=256
      - API_WEB3_JSON_RPC_FEE_HISTORY_LIMIT=100
      - API_WEB3_JSON_RPC_MAX_BATCH_REQUEST_SIZE=200
      - API_WEB3_JSON_RPC_WEBSOCKET_REQUESTS_PER_MrINUTE_LIMIT=10
      - API_CONTRACT_VERIFICATION_PORT=3070
      - API_CONTRACT_VERIFICATION_URL=http://127.0.0.1:3070
      - API_CONTRACT_VERIFICATION_THREADS_PER_SERVER=128
      - API_WEB3_JSON_RPC_MAX_RESPONSE_BODY_SIZE_MB=10
      - API_PROMETHEUS_LISTENER_PORT=3312
      - API_PROMETHEUS_PUSHGATEWAY_URL=http://127.0.0.1:9091
      - API_PROMETHEUS_PUSH_INTERVAL_MS=100
      - API_HEALTHCHECK_PORT=8081
      - API_MERKLE_TREE_PORT=8082
      - DATABASE_URL=postgres://postgres:postgres@localhost:5432/postgres # zksync node database
      - DATABASE_POOL_SIZE=50
